config/routes.rb
Rails.application.routes.draw do
  root "general#show"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/payment', to: 'general#payment'
  get '/mission', to: 'general#mission'
  get '/careers', to: 'general#careers'
  get '/employees', to: 'general#employees'
  get '/admin', to: 'general#admin', as: 'admin'
  get '/classrooms/admin', to: 'classrooms#admin'
  get '/programs/admin', to: 'programs#admin'
  get '/parent_resources/admin', to: 'parent_resources#admin'
  get '/collaborations/admin', to: 'collaborations#admin'
  get '/contacts/admin', to: 'contacts#admin'
  get '/benefits/admin', to: 'benefits#admin'
  get '/career_sites/admin', to: 'career_sites#admin'
  get '/employee_resources/admin', to: 'employee_resources#admin'
  get '/posts/admin', to: 'posts#admin'
  get '/admin/super', to: 'users#super', as: 'super_admin'
  post '/super', to: 'users#create_super'
  get '/carousel/admin', to: 'carousel#new'
  patch '/carousel/admin/:id', to: 'carousel#create', as: "carousel"
  resources :programs
  resources :classrooms
  resources :contacts
  resources :users, only: [:new, :create, :edit, :update, :destroy]
  resources :collaborations
  resources :posts
  resources :parent_resources
  resources :benefits, only: [:new, :create, :edit, :update, :destroy]
  resources :career_sites, only: [:new, :create, :edit, :update, :destroy]
  resources :employee_resources, only: [:new, :create, :edit, :update, :destroy]
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/benefit.rb
class Benefit < ApplicationRecord
  validates :benefit, presence: true
end

app/controllers/benefits_controller.rb
class BenefitsController < ApplicationController

  def new
    @benefit = Benefit.new
  end

  def create
    @benefit = Benefit.new(benefit_params)
    if @benefit.save
      flash[:notice] = "Success! Visit <a href='/careers'>published benefit</a>."
      redirect_to admin_path
    else
      @errors = @benefit.errors.messages
      flash[:notice] = @errors
      render :new
    end
  end

  def edit
    @benefit = Benefit.find(params[:id])
  end

  def update
    @benefit = Benefit.find(params[:id])
    if @benefit.update(benefit_params)
      flash[:notice] = "Success! Visit <a href='/careers'>published benefit</a>."
      redirect_to admin_path
    else
      @errors = @benefit.errors.messages
      flash[:notice] = @errors
      render :new
    end
  end

  def destroy
    @benefit = Benefit.find(params[:id])
    @benefit.destroy
    flash[:notice] = "Benefit deleted"
    redirect_to admin_path
  end

  def admin
    @benefits = Benefit.all.order('id DESC')
  end
  private

  def benefit_params
    params.require(:benefit).permit(:benefit)
  end
end

app/views/benefits/_form.html.erb
<%= form_for @benefit do |f| %>
  <%= f.label :benefit %>
  <%= f.text_area :benefit %>

  <%= f.submit 'submit', :class => "amber lighten-1 white-text btn", data: { confirm:
    "Ready to post this update? All changes will appear on the live SKCDC website." } %><br></br>
<% end %>

app/views/benefits/admin.html.erb
<%= render partial: "/general/admin_left_sidebar" %>

<div id="right-col" class="col l8 m8 s12 center-align">
  <h5 class="yellow-title">Edit Benefits</h5>
  <ul class="collection">
    <li class="collection-item"><%= link_to "+ new benefit", "/benefits/new" %></li>
  <% @benefits.each do |benefit| %>
    <li class="collection-item">
      <%= link_to "#{benefit.benefit}", edit_benefit_path(benefit) %>
    </li>
  <% end %>
</ul>

</div>

app/views/benefits/edit.html.erb
<div id="left-col" class="col l4 m4 s12 center-align">
  <h5><%= link_to "Admin Account", admin_path %></h5>
  <%= link_to "see published benefits", @benefit %>
  <hr class="yellow-rule">
  Does this benefit no longer exist?<br>
  <%= button_to "delete benefit", @benefit, :method => :delete, data: {confirm: "Are you sure you want to delete this benefit?"}, class: "amber lighten-1 white-text btn" %>
  <hr class="yellow-rule">
</div>

<div id="right-col" class='col l8 m8 s12'>
  <%= render partial: '/general/error_notice' %>
  <h5 class="yellow-title">Update Benefit</h5>
  <%= render partial: 'form' %>
</div>

app/views/benefits/new.html.erb
<%= render partial: "/general/admin_left_sidebar" %>

<div id="right-col" class='col l8 m8 s12'>
  <%= render partial: '/general/error_notice' %>
  <h5 class="yellow-title">New Benefit</h5>
  <%= render partial: 'form' %>
</div>