config/routes.rb
Rails.application.routes.draw do
  root "general#show"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/payment', to: 'general#payment'
  get '/mission', to: 'general#mission'
  get '/careers', to: 'general#careers'
  get '/employees', to: 'general#employees'
  get '/admin', to: 'general#admin', as: 'admin'
  get '/classrooms/admin', to: 'classrooms#admin'
  get '/programs/admin', to: 'programs#admin'
  get '/parent_resources/admin', to: 'parent_resources#admin'
  get '/collaborations/admin', to: 'collaborations#admin'
  get '/contacts/admin', to: 'contacts#admin'
  get '/benefits/admin', to: 'benefits#admin'
  get '/career_sites/admin', to: 'career_sites#admin'
  get '/employee_resources/admin', to: 'employee_resources#admin'
  get '/posts/admin', to: 'posts#admin'
  get '/admin/super', to: 'users#super', as: 'super_admin'
  post '/super', to: 'users#create_super'
  get '/carousel/admin', to: 'carousel#new'
  patch '/carousel/admin/:id', to: 'carousel#create', as: "carousel"
  resources :programs
  resources :classrooms
  resources :contacts
  resources :users, only: [:new, :create, :edit, :update, :destroy]
  resources :collaborations
  resources :posts
  resources :parent_resources
  resources :benefits, only: [:new, :create, :edit, :update, :destroy]
  resources :career_sites, only: [:new, :create, :edit, :update, :destroy]
  resources :employee_resources, only: [:new, :create, :edit, :update, :destroy]
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/career_site.rb
class CareerSite < ApplicationRecord
  validates :name, :url, presence: true
end

app/controllers/career_sites_controller.rb
class CareerSitesController < ApplicationController

  def new
    @career_site = CareerSite.new
  end

  def create
    @career_site = CareerSite.new(career_site_params)
    if @career_site.save
      flash[:notice] = "Success! Visit <a href='/careers'>published career site</a>."
      redirect_to admin_path
    else
      @errors = @career_site.errors.messages
      flash[:notice] = @errors
      render :new
    end
  end

  def edit
    @career_site = CareerSite.find(params[:id])
  end

  def update
    @career_site = CareerSite.find(params[:id])
    if @career_site.update(career_site_params)
      flash[:notice] = "Success! Visit <a href='/careers'>published career site</a>."
      redirect_to admin_path
    else
      @errors = @career_site.errors.messages
      flash[:notice] = @errors
      render :new
    end
  end

  def destroy
    @career_site = CareerSite.find(params[:id])
    @career_site.destroy
    flash[:notice] = "Career site deleted"
    redirect_to admin_path
  end

  def admin
    @career_sites = CareerSite.all.order('id DESC')
  end

  private

  def career_site_params
    params.require(:career_site).permit(:name, :url)
  end

end

app/views/career_sites/_form.html.erb
<%= form_for @career_site do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :url %>
  <%= f.text_field :url %>

  <%= f.submit 'submit', :class => "amber lighten-1 white-text btn", data: { confirm:
    "Ready to post this update? All changes will appear on the live SKCDC website." } %><br></br>
<% end %>

app/views/career_sites/admin.html.erb
<%= render partial: "/general/admin_left_sidebar" %>

<div id="right-col" class="col l8 m8 s12 center-align">
  <h5 class="yellow-title">Edit Career Sites</h5>
  <ul class="collection">
    <li class="collection-item"><%= link_to "+ new career site", "/career_sites/new" %></li>
  <% @career_sites.each do |site| %>
    <li class="collection-item">
      <%= link_to "#{site.name}", edit_career_site_path(site) %>
    </li>
  <% end %>
</ul>

</div>

app/views/career_sites/edit.html.erb
<div id="left-col" class="col l4 m4 s12 center-align">
  <h5><%= link_to "Admin Account", admin_path %></h5>
  <%= link_to "see published career site", '/careers' %>
  <hr class="yellow-rule">
  Does this career site no longer exist?<br>
  <%= button_to "delete career site", @career_site, :method => :delete, data: {confirm: "Are you sure you want to delete this career site?"}, class: "amber lighten-1 white-text btn" %>
  <hr class="yellow-rule">
</div>

<div id="right-col" class='col l8 m8 s12'>
  <%= render partial: '/general/error_notice' %>
  <h5 class="yellow-title">Update Career Site</h5>
  <%= render partial: 'form' %>
</div>

app/views/career_sites/new.html.erb
<%= render partial: "/general/admin_left_sidebar" %>

<div id="right-col" class='col l8 m8 s12'>
  <%= render partial: '/general/error_notice' %>
  <h5 class="yellow-title">New Career Site</h5>
  <%= render partial: 'form' %>
</div>