config/routes.rb
Rails.application.routes.draw do
  root "general#show"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/payment', to: 'general#payment'
  get '/mission', to: 'general#mission'
  get '/careers', to: 'general#careers'
  get '/employees', to: 'general#employees'
  get '/admin', to: 'general#admin', as: 'admin'
  get '/classrooms/admin', to: 'classrooms#admin'
  get '/programs/admin', to: 'programs#admin'
  get '/parent_resources/admin', to: 'parent_resources#admin'
  get '/collaborations/admin', to: 'collaborations#admin'
  get '/contacts/admin', to: 'contacts#admin'
  get '/benefits/admin', to: 'benefits#admin'
  get '/career_sites/admin', to: 'career_sites#admin'
  get '/employee_resources/admin', to: 'employee_resources#admin'
  get '/posts/admin', to: 'posts#admin'
  get '/admin/super', to: 'users#super', as: 'super_admin'
  post '/super', to: 'users#create_super'
  get '/carousel/admin', to: 'carousel#new'
  patch '/carousel/admin/:id', to: 'carousel#create', as: "carousel"
  resources :programs
  resources :classrooms
  resources :contacts
  resources :users, only: [:new, :create, :edit, :update, :destroy]
  resources :collaborations
  resources :posts
  resources :parent_resources
  resources :benefits, only: [:new, :create, :edit, :update, :destroy]
  resources :career_sites, only: [:new, :create, :edit, :update, :destroy]
  resources :employee_resources, only: [:new, :create, :edit, :update, :destroy]
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  validate :email_valid?



  def email_valid?
    if !email.include?("@skcdc.org")
      errors.add(:email, "must be an skcdc email")
    end
  end

  def self.super_count
     User.where(super: 'true').count
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user
  before_action :check_super

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.email.downcase!
    if @user.save
      flash[:notice] = "user created"
      redirect_to admin_path
     else
      flash.now[:notice] = "User emails must be unique SKCDC emails. Passwords must be six characters in length."
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      if User.super_count >= 1
        flash[:notice] = "user updated"
        redirect_to super_admin_path
      else
        @user.update(super: 'true')
        @user.errors.add(:super, "there must be at least 1 super admin")
        @errors = @user.errors.messages
        flash[:notice] = @errors
        render :edit
      end
    else
      @errors = @user.errors.messages
      flash[:notice] = @errors
      render :edit
    end
  end

  def super
    current_user
    @users = User.order(:email)
  end

def destroy
  @user = User.find(params[:id])
  @user.destroy
  redirect_to super_admin_path, :notice => "user deleted"
end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :super)
    end
end

app/views/users/edit.html.erb
<div id="left-col" class="col l4">
  Does this user no longer work here?<br>
  <%= button_to "delete user", @user, :method => :delete, data: {confirm: "Are you sure you want to delete this user?"}, class: "amber lighten-1 white-text btn" %>

</div>
<div id="right-col" class="col l6">
  <h3>Edit Admin User</h3>
  <%= render partial: '/general/error_notice' %>
<%= form_for(@user) do |f|%>

  <%= f.label :email %>
  <%= f.text_field :email %><br>

  <%= f.label :password %>
  <%= f.password_field :password %><br>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.check_box :super %>
  <%= f.label :super, "super admin" %>
  <br></br>


  <%= f.submit 'submit', :class => "waves-effect waves-light amber lighten-1 white-text btn" %><br></br>

<% end %>
<p><%= link_to "◁ return to super admin page", super_admin_path %></p>
</div>

app/views/users/logout.html.erb
<div>
  <%= button_to "logout", logout_path, method: "post", class: "waves-effect waves-light amber lighten-1 white-text btn" %>
</div>

app/views/users/new.html.erb
<%= render partial: "/general/admin_left_sidebar" %>

<div id="right-col" class='col l8 m8 s12'>
  <%= render partial: '/general/flash_notice' %>
  <h3>Create Admin Account </h3>
  <%= form_for(@user) do |f|%>
    <%= f.label :email %>
    <%= f.text_field :email %><br>

    <%= f.label :password %>
    <%= f.password_field :password %><br>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.check_box :super %>
    <%= f.label :super, "super admin" %>
    <br></br>
    <%= f.submit 'submit', :class => "amber lighten-1 white-text btn" %><br></br>
  <% end %>
</div>

app/views/users/super.html.erb
<div id="left-col" class="col l4 m4"></div>

<div id="right-col" class="col l7 m8">
  <h5>Create and Edit Users</h5>
    <div class="text-indent">
      <p><%= link_to "+ create new user", new_user_path %></p>
      <% @users.each do |user| %>
      <p><%= link_to "#{user.email}", edit_user_path(user) %></p>
      <% end %>
    </div>
    <br></br>
  <p><%= link_to "◁ return to admin main page", admin_path %></p>

</div>